'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.'''

# Fibonaçi'de 4 Milyona kadar olan çift sayıların toplamı

# Biri diğerinden bir eksik ve 2.'si 1 olacak şekilde 2 integer değişken ata
a, b = 0, 1
# Her defasında değerler ekleyeceğin ve neticede sonucumu tutacak değişkeni oluştur
sonuc = 0
# 2. değişken 4 milyondan küçük ( veya eşit ) olduğu sürece döngü devam etsin
while b <= 4000000:
# 2. değişken çift ise sonuca ekle
    if b % 2 == 0: sonuc += b
# 1. değişken 2. değişken, 2.değişken 1. + kendisi olsun
    a, b = b, a + b
    
print(sonuc)


























